name: Docker Build Test

on: [pull_request]
      
jobs:
  docker:
    env:
      BRANCH_NAME: ${GITHUB_REF##*/}

    runs-on: ubuntu-latest
    steps:
      - 
        name: Validate Branch
        run: echo ${{ env.BRANCH_NAME }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: runningmattress/jenkins-jcasc:${{ env.BRANCH_NAME }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}